version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - ${WORKSPACES}:/var/www/html/
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx/:/var/log/nginx/
    links:
      - php72:fpm72
      - php56:fpm56
    environment:
      - TZ=Asia/Shanghai
    networks:
      - frontend
      - backend
  php72:
    build: ./php/php72/
    expose:
      - "9000"
    volumes:
      - ${WORKSPACES}:/var/www/html/
      - ./conf/php/php72.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php-fpm.d/www72.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./log/php-fpm/:/var/log/php-fpm/
    links:
      - mysql:mysql
      - redis:redis
    networks:
      - frontend
      - backend
  php56:
    build: ./php/php56/
    expose:
      - "9000"
    volumes:
      - ${WORKSPACES}:/var/www/html/
      - ./conf/php/php56.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php-fpm.d/www56.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./log/php-fpm/:/var/log/php-fpm/
    links:
      - mysql:mysql
      - redis:redis
    networks:
      - backend
      - frontend

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/:/var/lib/mysql/
      - ./log/mysql/:/var/log/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - backend
  redis:
    image: redis:latest
    command: redis-server --requirepass sdongpo123
    ports:
      - "6379:6379"
    networks:
      - backend

  portainer:
    image: portainer/portainer:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/:/data
    networks:
      - backend
      - frontend
networks:
  frontend:
  backend:
